In [1]:
ages = [10,12,23,34,45,45,66,56,67,34,32,32,42,11,13,24,44,46,67,46]

In [2]:
len(ages)

20

In [3]:
import numpy as np
ages_mean=np.mean(ages)
print(ages_mean)

37.45


# Lets take sample

In [4]:
sample_size=10
age_sample = np.random.choice(ages,sample_size)

In [5]:
age_sample

array([66, 56, 12, 67, 34, 34, 46, 13, 23, 67])

In [6]:
from scipy.stats import ttest_1samp

In [7]:
ttest,p_value = ttest_1samp(age_sample,30)

In [8]:
print(p_value)

0.12074890570223969


In [9]:
if p_value < 0.05:
    print(' we are rejecting null hypothesis')
else:
    print('we are accepting null hypothesis')


we are accepting null hypothesis


we are accepting null hypothesis

## Some more examples

consider the age of students in a college in Class A

In [15]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import math
np.random.seed(6)
school_ages = stats.poisson.rvs(loc=18,mu=35,size=1500)
classA_ages = stats.poisson.rvs(loc=18,mu=30,size=60)

In [16]:
classA_ages.mean()

46.9

In [17]:
_,p_value = stats.ttest_1samp(a=classA_ages,popmean=school_ages.mean())

In [18]:
p_value

1.139027071016194e-13

In [19]:
school_ages.mean()

53.303333333333335

In [20]:
if p_value < 0.05:
    print(' we are rejecting null hypothesis')
else:
    print('we are accepting null hypothesis')


 we are rejecting null hypothesis


## Two-sample T-test

In [21]:
np.random.seed(12)
classB_ages = stats.poisson.rvs(loc=18,mu=33,size=60)
classB_ages.mean()

50.63333333333333

In [23]:
_,p_value = stats.ttest_ind(a=classA_ages,b=classB_ages,equal_var=False)

In [24]:
p_value

0.00039942095100859375

In [25]:
if p_value < 0.05:
    print(' we are rejecting null hypothesis')
else:
    print('we are accepting null hypothesis')


 we are rejecting null hypothesis


## Paired T-test 

In [35]:
weight1 = [25,30,28,35,28,34,26,29,30,26,28,32,31,30,45]
weight2 = weight1+stats.norm.rvs(scale=5,loc=1.25,size=15)

In [36]:
print(weight1)
print(weight2)


[25, 30, 28, 35, 28, 34, 26, 29, 30, 26, 28, 32, 31, 30, 45]
[30.46370697 36.63369994 31.53845269 23.15253339 32.94523171 38.58750529
 27.48201318 33.58038798 38.28974242 27.50574593 24.5701257  24.05445346
 32.56889364 27.68015951 43.44057668]


In [37]:
weight_df = pd.DataFrame({"weight_10":np.array(weight1),
                          "weight_20":np.array(weight2),
                          "weight_change":np.array(weight2)-np.array(weight1)})

In [38]:
weight_df

weight_10  weight_20  weight_change
0          25  30.463707       5.463707
1          30  36.633700       6.633700
2          28  31.538453       3.538453
3          35  23.152533     -11.847467
4          28  32.945232       4.945232
5          34  38.587505       4.587505
6          26  27.482013       1.482013
7          29  33.580388       4.580388
8          30  38.289742       8.289742
9          26  27.505746       1.505746
10         28  24.570126      -3.429874
11         32  24.054453      -7.945547
12         31  32.568894       1.568894
13         30  27.680160      -2.319840
14         45  43.440577      -1.559423

In [39]:
_,p_value = stats.ttest_rel(a=weight1,b=weight2)

In [40]:
print(p_value)

0.48505596890469815


In [41]:
if p_value < 0.05:
    print(' we are rejecting null hypothesis')
else:
    print('we are accepting null hypothesis')


we are accepting null hypothesis


## Chi-Square Test

The test is applied when you have two categorical variables from a single population. It is used to determine whether there is a significant association between the two variables. 

In [42]:
import scipy.stats as stats
import seaborn as sns
import pandas as pd
import numpy as np

In [44]:
dataset = sns.load_dataset('tips')

In [45]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [46]:
dataset_table = pd.crosstab(dataset['sex'],dataset['smoker'])
print(dataset_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [47]:
dataset_table.values

array([[60, 97],
       [33, 54]], dtype=int64)

In [49]:
#Observed Values
Observed_Values = dataset_table.values
print('Observed_Values :-\n',Observed_Values)

Observed_Values :-
 [[60 97]
 [33 54]]


In [50]:
val=stats.chi2_contingency(dataset_table)

In [51]:
val

(0.008763290531773594,
 0.925417020494423,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [52]:
Expected_Values=val[3]

In [53]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_of_columns=len(dataset_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [54]:
from scipy.stats import chi2

In [55]:
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [56]:
print('chi_square statistic:-',chi_square_statistic)

chi_square statistic:- 0.001934818536627623


In [57]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [61]:
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

p-value: 0.964915107315732
Significance level:  0.05
Degree of Freedom:  1
p-value: 0.964915107315732
